### ISSUE TITLE
Problems with themes

### ISSUE THREAD

**Issue by h-2** [leafac/shiki-latex#3]
```tex
\documentclass{scrartcl}

\usepackage{realboxes}
\usepackage{fontspec}

\newfontfamily\UbuntuMono{Ubuntu Mono}
\setmonofont{Ubuntu Mono}

\usepackage[table,svgnames]{xcolor}
\definecolor{lightgrey}{rgb}{0.9,0.9,0.9}
\definecolor{dsolar_back}{HTML}{FDF6E3}
\definecolor{dsolar_text}{HTML}{657B83}
\definecolor{teal}{HTML}{94ccbe}

\usepackage[letterspace=60]{microtype}

\usepackage{minted}

\setminted[c++]{
    linenos=true,
    bgcolor=dsolar_back,
    fontsize=\footnotesize,
%     style=solarizedlight,
%     style=solarized_light,
    frame=single,
    framesep=5pt,
    rulecolor=\color{lightgrey},
    stepnumber=2,
    numbersep=5pt,
    stripnl=false,
}

% Fix the frame overlapping the background
\makeatletter
\renewenvironment{minted@colorbg}[1]{
\setlength{\fboxsep}{\z@}
\def\minted@bgcol{#1}
\noindent
\begin{lrbox}{\minted@bgbox}
\begin{minipage}{\linewidth}}
{\end{minipage}
\end{lrbox}%
\colorbox{\minted@bgcol}{\usebox{\minted@bgbox}}}
\makeatother


\renewcommand\theFancyVerbLine{{\color{dsolar_text}\small\arabic{FancyVerbLine}}}

\renewcommand{\MintedPygmentize}{./node_modules/.bin/shiki-minted}

\usemintedstyle{zeit}

\begin{document}
\begin{minted}{c++}
template <typename Spec>
struct Base
{
    void foo()
    {
        std::cout << "base";
    }

    void bar()
    {
        /*...*/
        static_cast<Spec &>(*this).foo();
    }
};

std::vector vec{1, 7, /*...*/};
\end{minted}
\end{document}
```

Building this fails with:

```
/lmroman9-regular.luc)(load luc: /home/hannes/.texlive2015/texmf-var/luatex-cach
e/generic/fonts/otf/lmroman9-regular.luc)
! Undefined control sequence.
<argument> \@@scl 
       
l.12 ...FFF}{        }\textcolor[HTML]{888}{/*...*/}
```
If I remove the theme, it builds ok.

If I set the theme to `nord`, there is no error but the resulting PDF contains `FF` as characters everywhere.

**Comment by h-2** [comment]
Also, how can I add a custom theme? I tried going into `./node_modules/shiki-themes/data/vscode/` and copy e.g. `light_vs` to `custom` and then use "custom" as theme name, but it is not found...

Thank you for your help!

**Comment by leafac** [comment]
First of all, thanks for using my package and for contributing with these bug reports.

I fixed the bugs you mentioned and [added support for custom themes](https://github.com/leafac/shiki-latex#themes). It’s all in the [`1.1.0` release](https://www.npmjs.com/package/shiki-latex/v/1.1.0).

**Comment by h-2** [comment]
Thank you for providing the package! Things are starting to look really good for me! The ability to add your own local theme is really helpful :+1: 

Since the C++ grammer in Shiki is quite outdated, I have started modifying it. Would it be possible to also add a  latex knob for selecting user-provided grammers? e.g. 
```tex
\useshikigrammer{c++}{mycpp.json}
\useshikigrammer{c}{myc.json}
```

**Comment by leafac** [comment]
The good news is that minted already supports selecting different themes (what they call **styles**) for different languages and even per listing. You wouldn’t need `\useshikigrammer`, but could use `\usemintedstyle[language]{theme}`.

The bad news is that the way minted calls Pygments doesn’t make it easy for us to detect these theme changes. The information isn’t on the command line that calls Pygments, but embedded in LaTeX. So theme changes like these don’t work with Shiki LaTeX for now.

I want Shiki LaTeX to be a glue between minted and Shiki, not a LaTeX package in and of itself. For example, if we were to provide something like `\useshikigrammer`, then we’d need a `\usepackage{shiki-latex}` of some sort.

If you really need this, implement it and send a Pull Request and we can talk about it.

**Comment by leafac** [comment]
Oh, another thing you can do, since you’re willing to customize themes, is have a single theme with different rules for different languages.

And I encourage you to contribute back to Shiki with your grammar improvements (or even further upstream, since Shiki themes aren’t original; they’re just borrowed from other places).

**Comment by h-2** [comment]
> The good news is that minted already supports selecting different themes (what they call styles) for different languages and even per listing. You wouldn’t need \useshikigrammer, but could use `\usemintedstyle[language]{theme}`.

I am less interested in different themes, I just want to overwrite the grammar, because that is lacking.

> I want Shiki LaTeX to be a glue between minted and Shiki, not a LaTeX package in and of itself. For example, if we were to provide something like `\useshikigrammer`, then we’d need a `\usepackage{shiki-latex}` of some sort.

That's a very valid point, I understand that.

> And I encourage you to contribute back to Shiki with your grammar improvements (or even further upstream, since Shiki themes aren’t original; they’re just borrowed from other places).

I will definitely try to contribute many things back upstream once my thesis is done (but some changes are also specific to my work, e.g. a list of my libraries type-names).
