### ISSUE TITLE
Error when custom theme is in subfolder

### ISSUE THREAD

**Issue by h-2** [leafac/shiki-latex#5]
When using a custom style that is not in the local folder, e.g. `\usemintedstyle{./foobar/theme.json}`, there is an error that the file `_minted-NAME/foobar/theme.json.pygstyle` cannot be created.
The generated PDF looks ok, though!

A workaround is creating the subfolder `_minted-NAME/foobar/` after the which the file is correctly created. I guess you should just strip folder names somewhere before creating that file.

Thanks again for providing the tool and being so fast with fixing things!

**Comment by leafac** [comment]
Unfortunately this is on minted’s side and there’s nothing Shiki LaTeX can do about it: the error happens before we’re even called. That’s why the `README` says “don’t put [the custom theme file] under a folder because minted doesn’t support it.”

**Comment by h-2** [comment]
> “don’t put [the custom theme file] under a folder because minted doesn’t support it.”

My bad, sorry for the noise!

**Comment by leafac** [comment]
Don’t worry about it 😉
