### ISSUE TITLE
`stripnl=false` is ignored

### ISSUE THREAD

**Issue by h-2** [leafac/shiki-latex#6]
The minted-option `stripnl=false` prevents newlines at the end of code snippets to be stripped. I rely on this heavily to align snippets that are shown side-by-side and should have certain lines appear on the same height.

shiki-latex seems to ignore this option and always strips trailing blank lines.

**Comment by h-2** [comment]
`mathescape=true` and `texcomments` are also not handled, yet. I guess the second one is a superset of the first, so I would maybe not need the first one if the second one were available...

**Comment by leafac** [comment]
I fixed `stripnl` in 1.1.6 and opened #8 to address `mathescape`, `texcomments`, and so forth. As it turns out, minted is calling the syntax highlighter with command-line options that we can pick up and do something about (unlike theme selection, which it’s hiding under LaTeX wizardry).

**Comment by leafac** [comment]
@h-2: I added support for `math escape` in 1.2.0. More options to come…
