### ISSUE TITLE
language "text" is broken

### ISSUE THREAD

**Issue by h-2** [leafac/shiki-latex#9]
If I try to use "text" as language (which means no syntax-highlighting, but possibly other minted settings like font...) the build fails with :

```
(node:21052) UnhandledPromiseRejectionWarning: Error: Cannot tokenize plaintext
    at Object.codeToThemedTokens (/usr/home/hannes/tmp/node_modules/shiki/dist/highlighter.js:110:47)
```

A simple example would be to define `\newmintinline[mono]{text}{}` and then try to use `\mono{FOOBAR}`.

**Comment by leafac** [comment]
Thanks for reporting. Fixed in 1.3.0.
